name: hezma
description: "A new Flutter project."
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  appwrouter: ^0.2.7
  change_app_package_name: ^1.3.0
  curved_labeled_navigation_bar: ^2.0.2
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_pannable_rating_bar: ^2.7.2+1
  font_awesome_flutter: ^10.7.0
  geocoding: ^3.0.0
  go_router: ^14.2.1
  google_maps_flutter: ^2.2.2
  google_maps_flutter_android: ^2.12.1
  google_maps_flutter_platform_interface: ^2.8.0
  intl_phone_field: ^3.2.0
  latlong2: ^0.9.1
  location: ^6.0.0
  permission_handler: ^11.3.1
  pin_code_fields: ^8.0.1
  smooth_page_indicator: ^1.2.0
  timer_button: ^2.1.1

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/logos/
    - assets/images/

  fonts:
    - family: alfont
      fonts:
        - asset: assets/fonts/alfont_com_AlFont_com_STV.ttf
    - family: ArbFONTS-STV
      fonts:
        - asset: assets/fonts/ArbFONTS-STV.ttf
    - family: STVBold
      fonts:
        - asset: assets/fonts/STVBold.ttf

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logos/appicon.png"
